from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
from datetime import datetime
import io

class PDFReportGenerator:
    def __init__(self, company_name="Financial Close Report", generated_by="Trial Balance Assistant"):
        self.company_name = company_name
        self.generated_by = generated_by
        self.styles = getSampleStyleSheet()
        self.define_custom_styles()
        
    def define_custom_styles(self):
        """Define custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=colors.HexColor('#1a3a52'),
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='Subheading',
            parent=self.styles['Heading2'],
            fontSize=12,
            textColor=colors.HexColor('#2c5282'),
            spaceAfter=8,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='NormalText',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#333333')
        ))
    
    def generate_trial_balance_pdf(self, trial_balance_df, summary, filename=None):
        """Generate PDF report for trial balance"""
        if filename is None:
            filename = f"trial_balance_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.5*inch, bottomMargin=0.5*inch)
        story = []
        
        # Title
        story.append(Paragraph(self.company_name, self.styles['CustomTitle']))
        story.append(Paragraph("Trial Balance Report", self.styles['Subheading']))
        story.append(Spacer(1, 0.2*inch))
        
        # Report metadata
        meta_text = f"""
        <b>Generated by:</b> {self.generated_by}<br/>
        <b>Date:</b> {summary.get('generated_date', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))}<br/>
        <b>Total Accounts:</b> {summary.get('num_accounts', 0)}<br/>
        """
        story.append(Paragraph(meta_text, self.styles['NormalText']))
        story.append(Spacer(1, 0.3*inch))
        
        # Summary table
        summary_data = [
            ['Metric', 'Amount', 'Status'],
            [f"Total Debits", f"₹{summary.get('total_debit', 0):,.2f}", ""],
            [f"Total Credits", f"₹{summary.get('total_credit', 0):,.2f}", ""],
            [f"Difference", f"₹{summary.get('difference', 0):,.2f}", 
             "✓ BALANCED" if summary.get('is_balanced') else "✗ NOT BALANCED"]
        ]
        
        summary_table = Table(summary_data, colWidths=[2.5*inch, 2*inch, 1.5*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c5282')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Trial balance table
        story.append(Paragraph("Detailed Trial Balance", self.styles['Subheading']))
        story.append(Spacer(1, 0.1*inch))
        
        # Prepare TB data
        tb_data = [['Account Code', 'Account Name', 'Debit (₹)', 'Credit (₹)', 'Balance (₹)']]
        
        for idx, row in trial_balance_df.iterrows():
            tb_data.append([
                str(row['Account_Code']),
                str(row['Account_Name'])[:30],  # Truncate long names
                f"{row['Debit']:,.2f}",
                f"{row['Credit']:,.2f}",
                f"{row['Net_Balance']:,.2f}"
            ])
        
        # Add totals row
        tb_data.append([
            '',
            'TOTALS',
            f"{trial_balance_df['Debit'].sum():,.2f}",
            f"{trial_balance_df['Credit'].sum():,.2f}",
            ''
        ])
        
        tb_table = Table(tb_data, colWidths=[1.2*inch, 2*inch, 1.3*inch, 1.3*inch, 1.2*inch])
        tb_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c5282')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'RIGHT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('BACKGROUND', (0, 1), (-1, -2), colors.white),
            ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#d4e4f7')),
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#f0f0f0')])
        ]))
        story.append(tb_table)
        story.append(Spacer(1, 0.2*inch))
        
        # Footer
        footer_text = "<i>This report was generated by Trial Balance Assistant. Please review before month-end close.</i>"
        story.append(Paragraph(footer_text, self.styles['NormalText']))
        
        # Build PDF
        doc.build(story)
        buffer.seek(0)
        
        return buffer
    
    def generate_reconciliation_pdf(self, trial_balance_df, reconciliation_report, filename=None):
        """Generate PDF report for reconciliation findings"""
        if filename is None:
            filename = f"reconciliation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.5*inch, bottomMargin=0.5*inch)
        story = []
        
        # Title
        story.append(Paragraph(self.company_name, self.styles['CustomTitle']))
        story.append(Paragraph("Reconciliation & Review Report", self.styles['Subheading']))
        story.append(Spacer(1, 0.2*inch))
        
        # Overall status
        status = reconciliation_report.get('overall_status', 'UNKNOWN')
        status_color = colors.green if 'READY' in status else colors.red
        status_text = f"<font color='#{status_color.hexval()}'><b>{status}</b></font>"
        story.append(Paragraph(f"Status: {status_text}", self.styles['NormalText']))
        story.append(Spacer(1, 0.2*inch))
        
        # Balance check results
        story.append(Paragraph("1. Balance Check", self.styles['Subheading']))
        balance = reconciliation_report['balance_status']
        balance_text = f"""
        <b>Debits:</b> ₹{balance['total_debit']:,.2f}<br/>
        <b>Credits:</b> ₹{balance['total_credit']:,.2f}<br/>
        <b>Difference:</b> ₹{balance['difference']:,.2f}<br/>
        <b>Result:</b> <font color="{'green' if balance['is_balanced'] else 'red'}">{'✓ BALANCED' if balance['is_balanced'] else '✗ NOT BALANCED'}</font>
        """
        story.append(Paragraph(balance_text, self.styles['NormalText']))
        story.append(Spacer(1, 0.2*inch))
        
        # Suspicious entries
        story.append(Paragraph("2. Flagged Issues", self.styles['Subheading']))
        suspicious = reconciliation_report.get('suspicious_entries', [])
        
        if len(suspicious) > 0:
            sus_data = [['Account Code', 'Account Name', 'Issue', 'Severity']]
            for item in suspicious[:15]:  # Limit to 15 for space
                sus_data.append([
                    str(item['Account_Code']),
                    str(item['Account_Name'])[:25],
                    str(item['Issue'])[:30],
                    str(item['Severity'])
                ])
            
            sus_table = Table(sus_data, colWidths=[1.2*inch, 1.8*inch, 2.5*inch, 1*inch])
            sus_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#d35400')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#ffe6cc')])
            ]))
            story.append(sus_table)
        else:
            story.append(Paragraph("✓ No issues detected", self.styles['NormalText']))
        
        story.append(Spacer(1, 0.2*inch))
        
        # Round amounts
        round_amounts = reconciliation_report.get('round_amounts', [])
        if len(round_amounts) > 0:
            story.append(Paragraph("3. Round Amount Entries", self.styles['Subheading']))
            story.append(Paragraph(f"Found {len(round_amounts)} accounts with suspiciously round amounts (potential manual entries)", 
                                 self.styles['NormalText']))
            story.append(Spacer(1, 0.1*inch))
        
        # Build PDF
        doc.build(story)
        buffer.seek(0)
        
        return buffer
